# -*- python -*-
import os
from lsst.sconsUtils import scripts, env, targets

# This is more complicated than an examples SConscript should usually be (most can just use
# BasicSConscript.examples() with no arguments), because we have a source file that's compiled
# into both a C++ program and a pybind11 module.

ccList = []
for path in Glob("#examples/*.cc"):
    base, name = os.path.split(path.abspath)
    ccList.append(name)

scripts.BasicSConscript.examples(
    ccList=ccList,
)
